services:
  # 백엔드 + 프론트엔드 통합 서비스
  - type: web
    name: financial-statement-app
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt &&
      python download_corp_code.py &&
      python init_db.py &&
      cd frontend &&
      npm install &&
      npm run build &&
      cd ..
    startCommand: python backend/main.py
    envVars:
      - key: DART_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true
