services:
  # 백엔드 + 프론트엔드 통합 서비스 (Docker)
  - type: web
    name: financial-statement-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DART_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true
